<template><div><h1 id="rag-chunk-知识" tabindex="-1"><a class="header-anchor" href="#rag-chunk-知识"><span>RAG Chunk 知识</span></a></h1>
<p>Chunk 的目标不是“切得越碎越好”，而是让每个片段既能保留上下文，又方便检索命中。</p>
<h2 id="一、基础切分" tabindex="-1"><a class="header-anchor" href="#一、基础切分"><span>一、基础切分</span></a></h2>
<h3 id="_1-固定长度切分" tabindex="-1"><a class="header-anchor" href="#_1-固定长度切分"><span>1. 固定长度切分</span></a></h3>
<p>最简单的方式，按字符数、词数或 token 数硬切。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">chunkTextByFixedLength</span><span class="token punctuation">(</span>text<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> rawOptions<span class="token operator">:</span> Pick<span class="token operator">&lt;</span>ChunkingOptions<span class="token punctuation">,</span> <span class="token string">"chunkSize"</span> <span class="token operator">|</span> <span class="token string">"chunkOverlap"</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> options <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token operator">...</span><span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">,</span> <span class="token operator">...</span>rawOptions <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> normalizedText <span class="token operator">=</span> <span class="token function">normalizeLineEndings</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>normalizedText<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">const</span> chunks<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">let</span> cursor <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">while</span> <span class="token punctuation">(</span>cursor <span class="token operator">&lt;</span> normalizedText<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">const</span> end <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>normalizedText<span class="token punctuation">.</span>length<span class="token punctuation">,</span> cursor <span class="token operator">+</span> options<span class="token punctuation">.</span>chunkSize<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">const</span> chunk <span class="token operator">=</span> normalizedText<span class="token punctuation">.</span><span class="token function">slice</span><span class="token punctuation">(</span>cursor<span class="token punctuation">,</span> end<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">if</span> <span class="token punctuation">(</span>chunk<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			chunks<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>chunk<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">		<span class="token keyword">if</span> <span class="token punctuation">(</span>end <span class="token operator">>=</span> normalizedText<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			<span class="token keyword">break</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">		cursor <span class="token operator">=</span> Math<span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span>end <span class="token operator">-</span> options<span class="token punctuation">.</span>chunkOverlap<span class="token punctuation">,</span> cursor <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> chunks<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>适用场景</strong></p>
<ul>
<li>先把系统跑起来</li>
<li>文档结构不明显</li>
<li>对稳定性要求高于召回质量</li>
</ul>
<h3 id="_2-递归切分" tabindex="-1"><a class="header-anchor" href="#_2-递归切分"><span>2. 递归切分</span></a></h3>
<p>先按大结构切，再逐层细分，直到满足长度限制。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">chunkTextRecursively</span><span class="token punctuation">(</span></span>
<span class="line">	text<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span></span>
<span class="line">	rawOptions<span class="token operator">:</span> Pick<span class="token operator">&lt;</span>ChunkingOptions<span class="token punctuation">,</span> <span class="token string">"chunkSize"</span> <span class="token operator">|</span> <span class="token string">"chunkOverlap"</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> options <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token operator">...</span><span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">,</span> <span class="token operator">...</span>rawOptions <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> normalizedText <span class="token operator">=</span> <span class="token function">normalizeLineEndings</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>normalizedText<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> <span class="token function">splitByHierarchy</span><span class="token punctuation">(</span>normalizedText<span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token string">"\n\n"</span><span class="token punctuation">,</span> <span class="token string">"\n"</span><span class="token punctuation">,</span> <span class="token string">". "</span><span class="token punctuation">,</span> <span class="token string">"? "</span><span class="token punctuation">,</span> <span class="token string">"! "</span><span class="token punctuation">,</span> <span class="token string">"; "</span><span class="token punctuation">,</span> <span class="token string">" "</span><span class="token punctuation">,</span> <span class="token string">""</span><span class="token punctuation">]</span><span class="token punctuation">,</span> options<span class="token punctuation">.</span>chunkSize<span class="token punctuation">,</span> options<span class="token punctuation">.</span>chunkOverlap<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-基于句子的切分" tabindex="-1"><a class="header-anchor" href="#_3-基于句子的切分"><span>3. 基于句子的切分</span></a></h3>
<p>按句号、问号、分号等边界切分，再按长度控制合并。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">chunkTextBySentence</span><span class="token punctuation">(</span>text<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> normalized <span class="token operator">=</span> <span class="token function">normalizeLineEndings</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>normalized<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">const</span> sentences <span class="token operator">=</span> <span class="token function">isChineseDominant</span><span class="token punctuation">(</span>normalized<span class="token punctuation">)</span> <span class="token operator">?</span> <span class="token function">splitChineseSentences</span><span class="token punctuation">(</span>normalized<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token function">splitEnglishSentences</span><span class="token punctuation">(</span>normalized<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">return</span> sentences<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span> <span class="token operator">?</span> sentences <span class="token operator">:</span> <span class="token punctuation">[</span>normalized<span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、结构切分" tabindex="-1"><a class="header-anchor" href="#二、结构切分"><span>二、结构切分</span></a></h2>
<h3 id="_1-markdown-切分" tabindex="-1"><a class="header-anchor" href="#_1-markdown-切分"><span>1. Markdown 切分</span></a></h3>
<p>按标题层级、段落、代码块切。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">buildMarkdownRagIngestBody</span><span class="token punctuation">(</span>input<span class="token operator">:</span> ChunkDocumentInput<span class="token punctuation">,</span> rawOptions<span class="token operator">:</span> ChunkingOptions <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> RagIngestBody <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> options <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token operator">...</span><span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">,</span> <span class="token operator">...</span>rawOptions <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> cleanedContent <span class="token operator">=</span> <span class="token function">normalizeMarkdownContent</span><span class="token punctuation">(</span>input<span class="token punctuation">.</span>content<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> title <span class="token operator">=</span> input<span class="token punctuation">.</span>title<span class="token operator">?.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token function">extractTitle</span><span class="token punctuation">(</span>cleanedContent<span class="token punctuation">,</span> input<span class="token punctuation">.</span>relativePath<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> documentId <span class="token operator">=</span> <span class="token function">buildDocumentId</span><span class="token punctuation">(</span>input<span class="token punctuation">.</span>relativePath<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> sections <span class="token operator">=</span> <span class="token function">splitIntoSections</span><span class="token punctuation">(</span>cleanedContent<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> chunks<span class="token operator">:</span> RagIngestBody<span class="token punctuation">[</span><span class="token string">"chunks"</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">let</span> nextChunkIndex <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> section <span class="token keyword">of</span> sections<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">const</span> result <span class="token operator">=</span> <span class="token function">chunkSection</span><span class="token punctuation">(</span>section<span class="token punctuation">,</span> documentId<span class="token punctuation">,</span> input<span class="token punctuation">.</span>relativePath<span class="token punctuation">,</span> options<span class="token punctuation">,</span> nextChunkIndex<span class="token punctuation">,</span> input<span class="token punctuation">.</span>metadata<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		chunks<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token operator">...</span>result<span class="token punctuation">.</span>chunks<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		nextChunkIndex <span class="token operator">=</span> result<span class="token punctuation">.</span>nextChunkIndex<span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> <span class="token function">assembleRagIngestBody</span><span class="token punctuation">(</span></span>
<span class="line">		<span class="token punctuation">{</span></span>
<span class="line">			documentId<span class="token punctuation">,</span></span>
<span class="line">			namespace<span class="token operator">:</span> options<span class="token punctuation">.</span>namespace<span class="token punctuation">,</span></span>
<span class="line">			title<span class="token punctuation">,</span></span>
<span class="line">			metadata<span class="token operator">:</span> input<span class="token punctuation">.</span>metadata<span class="token punctuation">,</span></span>
<span class="line">		<span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">		chunks<span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">function</span> <span class="token function">chunkSection</span><span class="token punctuation">(</span></span>
<span class="line">	section<span class="token operator">:</span> MarkdownSection<span class="token punctuation">,</span></span>
<span class="line">	documentId<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span></span>
<span class="line">	relativePath<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span></span>
<span class="line">	options<span class="token operator">:</span> Required<span class="token operator">&lt;</span>Pick<span class="token operator">&lt;</span>ChunkingOptions<span class="token punctuation">,</span></span>
<span class="line">		<span class="token operator">|</span> <span class="token string">"namespace"</span></span>
<span class="line">		<span class="token operator">|</span> <span class="token string">"targetChineseChars"</span></span>
<span class="line">		<span class="token operator">|</span> <span class="token string">"maxChineseChars"</span></span>
<span class="line">		<span class="token operator">|</span> <span class="token string">"overlapChineseChars"</span></span>
<span class="line">		<span class="token operator">|</span> <span class="token string">"targetEnglishWords"</span></span>
<span class="line">		<span class="token operator">|</span> <span class="token string">"maxEnglishWords"</span></span>
<span class="line">		<span class="token operator">|</span> <span class="token string">"overlapEnglishWords"</span></span>
<span class="line">	<span class="token operator">>></span><span class="token punctuation">,</span></span>
<span class="line">	startChunkIndex<span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">,</span></span>
<span class="line">	metadata<span class="token operator">?</span><span class="token operator">:</span> RagMetadata<span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token punctuation">{</span> chunks<span class="token operator">:</span> RagIngestBody<span class="token punctuation">[</span><span class="token string">"chunks"</span><span class="token punctuation">]</span><span class="token punctuation">;</span> nextChunkIndex<span class="token operator">:</span> <span class="token builtin">number</span> <span class="token punctuation">}</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> chunks<span class="token operator">:</span> RagIngestBody<span class="token punctuation">[</span><span class="token string">"chunks"</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> sectionPath <span class="token operator">=</span> section<span class="token punctuation">.</span>headingPath<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">" > "</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">let</span> chunkIndex <span class="token operator">=</span> startChunkIndex<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> block <span class="token keyword">of</span> section<span class="token punctuation">.</span>blocks<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">const</span> parts <span class="token operator">=</span> <span class="token function">splitBlock</span><span class="token punctuation">(</span>block<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> part <span class="token keyword">of</span> parts<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			<span class="token keyword">const</span> text <span class="token operator">=</span> part<span class="token punctuation">.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">			<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>text<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">				<span class="token keyword">continue</span><span class="token punctuation">;</span></span>
<span class="line">			<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">			chunks<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">				chunkId<span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>documentId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">:</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token function">String</span><span class="token punctuation">(</span>chunkIndex<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">padStart</span><span class="token punctuation">(</span><span class="token number">4</span><span class="token punctuation">,</span> <span class="token string">"0"</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span></span>
<span class="line">				index<span class="token operator">:</span> chunkIndex<span class="token punctuation">,</span></span>
<span class="line">				text<span class="token punctuation">,</span></span>
<span class="line">				metadata<span class="token operator">:</span> <span class="token function">buildChunkMetadata</span><span class="token punctuation">(</span>relativePath<span class="token punctuation">,</span> sectionPath<span class="token punctuation">,</span> text<span class="token punctuation">,</span> metadata<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">			<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">			chunkIndex <span class="token operator">+=</span> <span class="token number">1</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">		chunks<span class="token operator">:</span> <span class="token function">mergeTinyTailChunks</span><span class="token punctuation">(</span>chunks<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">		nextChunkIndex<span class="token operator">:</span> chunkIndex<span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-对话式切分" tabindex="-1"><a class="header-anchor" href="#_2-对话式切分"><span>2. 对话式切分</span></a></h3>
<p>按角色和轮次切，比如 user / assistant、Q / A。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">buildDialogueRagIngestBody</span><span class="token punctuation">(</span>input<span class="token operator">:</span> ChunkDocumentInput<span class="token punctuation">,</span> rawOptions<span class="token operator">:</span> ChunkingOptions <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> RagIngestBody <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> options <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token operator">...</span><span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">,</span> <span class="token operator">...</span>rawOptions <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> content <span class="token operator">=</span> <span class="token function">normalizeMarkdownContent</span><span class="token punctuation">(</span>input<span class="token punctuation">.</span>content<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> documentId <span class="token operator">=</span> <span class="token function">buildDocumentId</span><span class="token punctuation">(</span>input<span class="token punctuation">.</span>relativePath<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> title <span class="token operator">=</span> input<span class="token punctuation">.</span>title<span class="token operator">?.</span><span class="token function">trim</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token function">extractTitle</span><span class="token punctuation">(</span>content<span class="token punctuation">,</span> input<span class="token punctuation">.</span>relativePath<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> turns <span class="token operator">=</span> <span class="token function">parseDialogueTurns</span><span class="token punctuation">(</span>content<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> chunks <span class="token operator">=</span> <span class="token function">groupDialogueTurns</span><span class="token punctuation">(</span>turns<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span>text<span class="token punctuation">,</span> index<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">createRagChunk</span><span class="token punctuation">(</span>documentId<span class="token punctuation">,</span> index<span class="token punctuation">,</span> text<span class="token punctuation">,</span> input<span class="token punctuation">.</span>metadata<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> <span class="token function">assembleRagIngestBody</span><span class="token punctuation">(</span></span>
<span class="line">		<span class="token punctuation">{</span></span>
<span class="line">			documentId<span class="token punctuation">,</span></span>
<span class="line">			namespace<span class="token operator">:</span> options<span class="token punctuation">.</span>namespace<span class="token punctuation">,</span></span>
<span class="line">			title<span class="token punctuation">,</span></span>
<span class="line">			metadata<span class="token operator">:</span> input<span class="token punctuation">.</span>metadata<span class="token punctuation">,</span></span>
<span class="line">		<span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">		chunks<span class="token punctuation">,</span></span>
<span class="line">	<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="三、语义切分" tabindex="-1"><a class="header-anchor" href="#三、语义切分"><span>三、语义切分</span></a></h2>
<h3 id="_1-语义切分" tabindex="-1"><a class="header-anchor" href="#_1-语义切分"><span>1. 语义切分</span></a></h3>
<p>根据相邻段落的语义相似度决定是否合并。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">semanticChunkParagraphs</span><span class="token punctuation">(</span>paragraphs<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> options<span class="token operator">:</span> Pick<span class="token operator">&lt;</span>ChunkingOptions<span class="token punctuation">,</span> <span class="token string">"semanticThreshold"</span> <span class="token operator">|</span> <span class="token string">"chunkSize"</span> <span class="token operator">|</span> <span class="token string">"chunkOverlap"</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> mergedParagraphs<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> threshold <span class="token operator">=</span> options<span class="token punctuation">.</span>semanticThreshold <span class="token operator">??</span> <span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">.</span>semanticThreshold<span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> targetSize <span class="token operator">=</span> options<span class="token punctuation">.</span>chunkSize <span class="token operator">??</span> <span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">.</span>chunkSize<span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> overlap <span class="token operator">=</span> options<span class="token punctuation">.</span>chunkOverlap <span class="token operator">??</span> <span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">.</span>chunkOverlap<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">let</span> current<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">let</span> currentKeywords<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">const</span> paragraph <span class="token keyword">of</span> paragraphs<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">const</span> paragraphKeywords <span class="token operator">=</span> <span class="token function">extractKeywords</span><span class="token punctuation">(</span>paragraph<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">const</span> similarity <span class="token operator">=</span> currentKeywords<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span> <span class="token operator">?</span> <span class="token function">jaccardSimilarity</span><span class="token punctuation">(</span>currentKeywords<span class="token punctuation">,</span> paragraphKeywords<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token keyword">const</span> candidate <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token operator">...</span>current<span class="token punctuation">,</span> paragraph<span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">		<span class="token keyword">if</span> <span class="token punctuation">(</span>candidate<span class="token punctuation">.</span>length <span class="token operator">&lt;=</span> targetSize <span class="token operator">&amp;&amp;</span> similarity <span class="token operator">>=</span> threshold<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			current <span class="token operator">=</span> candidate<span class="token punctuation">;</span></span>
<span class="line">			currentKeywords <span class="token operator">=</span> <span class="token function">extractKeywords</span><span class="token punctuation">(</span>current<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">"\n\n"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">			<span class="token keyword">continue</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">		<span class="token keyword">if</span> <span class="token punctuation">(</span>current<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">			mergedParagraphs<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>current<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">"\n\n"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">		current <span class="token operator">=</span> current<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span> <span class="token operator">&amp;&amp;</span> overlap <span class="token operator">></span> <span class="token number">0</span> <span class="token operator">?</span> current<span class="token punctuation">.</span><span class="token function">slice</span><span class="token punctuation">(</span><span class="token operator">-</span>overlap<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span></span>
<span class="line">		current<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>paragraph<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">		currentKeywords <span class="token operator">=</span> <span class="token function">extractKeywords</span><span class="token punctuation">(</span>current<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">"\n\n"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">if</span> <span class="token punctuation">(</span>current<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		mergedParagraphs<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>current<span class="token punctuation">.</span><span class="token function">join</span><span class="token punctuation">(</span><span class="token string">"\n\n"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">return</span> mergedParagraphs<span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span>Boolean<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-主题切分" tabindex="-1"><a class="header-anchor" href="#_2-主题切分"><span>2. 主题切分</span></a></h3>
<p>按主题聚类或主题变化点切分。</p>
<h3 id="_3-基于相似度的段落合并" tabindex="-1"><a class="header-anchor" href="#_3-基于相似度的段落合并"><span>3. 基于相似度的段落合并</span></a></h3>
<p>先按段落切，再根据相似度和长度阈值合并。</p>
<h2 id="四、高级切分" tabindex="-1"><a class="header-anchor" href="#四、高级切分"><span>四、高级切分</span></a></h2>
<h3 id="_1-parent-child-chunk" tabindex="-1"><a class="header-anchor" href="#_1-parent-child-chunk"><span>1. Parent-Child Chunk</span></a></h3>
<p>把大块内容当 parent，小块内容当 child。</p>
<h3 id="_2-agentic-chunk" tabindex="-1"><a class="header-anchor" href="#_2-agentic-chunk"><span>2. Agentic Chunk</span></a></h3>
<p>让模型参与判断切分边界。</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">buildAgenticRagIngestBody</span><span class="token punctuation">(</span>input<span class="token operator">:</span> ChunkDocumentInput<span class="token punctuation">,</span> rawOptions<span class="token operator">:</span> ChunkingOptions <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> RagIngestBody <span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">const</span> options <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token operator">...</span><span class="token constant">DEFAULT_OPTIONS</span><span class="token punctuation">,</span> <span class="token operator">...</span>rawOptions <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> content <span class="token operator">=</span> <span class="token function">normalizeMarkdownContent</span><span class="token punctuation">(</span>input<span class="token punctuation">.</span>content<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> paragraphs <span class="token operator">=</span> <span class="token function">splitParagraphs</span><span class="token punctuation">(</span>content<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> hasMarkdownStructure <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^#{1,6}\s+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">m</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>content<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">```</span><span class="token regex-delimiter">/</span><span class="token regex-flags">u</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>content<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> hasDialogueStructure <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^[^\n:：]{1,32}[:：]\s+</span><span class="token regex-delimiter">/</span><span class="token regex-flags">m</span></span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>content<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token keyword">const</span> longDocument <span class="token operator">=</span> paragraphs<span class="token punctuation">.</span>length <span class="token operator">>=</span> <span class="token number">4</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">	<span class="token comment">// 先按内容特征选最贴近的切分方式。</span></span>
<span class="line">	<span class="token keyword">if</span> <span class="token punctuation">(</span>hasMarkdownStructure<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token function">buildMarkdownRagIngestBody</span><span class="token punctuation">(</span>input<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">if</span> <span class="token punctuation">(</span>hasDialogueStructure<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token function">buildDialogueRagIngestBody</span><span class="token punctuation">(</span>input<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token keyword">if</span> <span class="token punctuation">(</span>longDocument<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">		<span class="token keyword">return</span> <span class="token function">buildSemanticRagIngestBody</span><span class="token punctuation">(</span>input<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">	<span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">	<span class="token comment">// 都不明显时，回退到最稳的固定长度切分。</span></span>
<span class="line">	<span class="token keyword">return</span> <span class="token function">buildFixedLengthRagIngestBody</span><span class="token punctuation">(</span>input<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-自适应切分" tabindex="-1"><a class="header-anchor" href="#_3-自适应切分"><span>3. 自适应切分</span></a></h3>
<p>根据文档类型自动选择策略。</p>
<h2 id="五、混合切分" tabindex="-1"><a class="header-anchor" href="#五、混合切分"><span>五、混合切分</span></a></h2>
<p>混合切分的核心是：不要只依赖一种边界。</p>
<h3 id="常见组合" tabindex="-1"><a class="header-anchor" href="#常见组合"><span>常见组合</span></a></h3>
<ul>
<li>Markdown + 固定长度</li>
<li>语义 + 固定长度</li>
<li>章节 + 句子</li>
<li>Parent-Child + 结构切分</li>
</ul>
<h3 id="适合什么情况" tabindex="-1"><a class="header-anchor" href="#适合什么情况"><span>适合什么情况</span></a></h3>
<ul>
<li>你希望 chunk 既稳定又不太粗</li>
<li>文档类型不统一</li>
<li>召回效果比实现简单更重要</li>
</ul>
<h2 id="六、选型建议" tabindex="-1"><a class="header-anchor" href="#六、选型建议"><span>六、选型建议</span></a></h2>
<ul>
<li><strong>先上线</strong>：固定长度 / 递归切分</li>
<li><strong>文档型内容</strong>：Markdown / 章节切分</li>
<li><strong>问答和对话</strong>：对话切分</li>
<li><strong>长文和复杂内容</strong>：语义切分</li>
<li><strong>追求更高质量</strong>：混合切分</li>
</ul>
<h2 id="七、和代码实现的关系" tabindex="-1"><a class="header-anchor" href="#七、和代码实现的关系"><span>七、和代码实现的关系</span></a></h2>
<p>现在项目里的实现可以当成这份知识文档的代码参考：</p>
<ul>
<li><code v-pre>src/common/rag/chunk/basic/</code></li>
<li><code v-pre>src/common/rag/chunk/structured/</code></li>
<li><code v-pre>src/common/rag/chunk/semantic/</code></li>
<li><code v-pre>src/common/rag/chunk/hybrid/</code></li>
</ul>
<p>如果后续继续补内容，建议按“方法原理 / 适用场景 / 代码实现 / 选型建议”这个顺序展开。</p>
</div></template>


